pipeline {
    agent {
        any
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build native image') {
            steps {
                sh 'mvn -B clean package -Pnative -DskipTests -Dquarkus.native.container-build=true'
            }
        }
        stage('Clean Old Containers') {
            steps {
                sh 'echo "TODO clean old resources..."'
            }
        }
        stage('Run native image') {
            steps {
                sh 'target/pg-runner'
            }
        }
    }
}