pipeline {
    agent {
        any{}
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build native image') {
            steps {
                sh 'mvn package -Pnative -DskipTests'
            }
        }
        stage('Kill old process running..') {
            steps {
                sh 'echo "TODO clean old resources...test"'
            }
        }
        stage('Run native image') {
            steps {
                sh 'target/pg-runner &'
            }
        }
    }
}